//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

package main

var layout = apiInfo{
	"BGPPeerService": {
		"changeBgpPeersForVpc",
		"createBgpPeer",
		"dedicateBgpPeer",
		"deleteBgpPeer",
		"listBgpPeers",
		"releaseBgpPeer",
		"updateBgpPeer",
	},
	"LoadBalancerService": {
		"assignCertToLoadBalancer",
		"assignToGlobalLoadBalancerRule",
		"assignToLoadBalancerRule",
		"createGlobalLoadBalancerRule",
		"createLBHealthCheckPolicy",
		"createLBStickinessPolicy",
		"createLoadBalancer",
		"createLoadBalancerRule",
		"deleteGlobalLoadBalancerRule",
		"deleteLBHealthCheckPolicy",
		"deleteLBStickinessPolicy",
		"deleteLoadBalancer",
		"deleteLoadBalancerRule",
		"deleteServicePackageOffering",
		"deleteSslCert",
		"deployNetscalerVpx",
		"listGlobalLoadBalancerRules",
		"listLBHealthCheckPolicies",
		"listLBStickinessPolicies",
		"listLoadBalancerRuleInstances",
		"listLoadBalancerRules",
		"listLoadBalancers",
		"listRegisteredServicePackages",
		"listSslCerts",
		"removeCertFromLoadBalancer",
		"removeFromGlobalLoadBalancerRule",
		"removeFromLoadBalancerRule",
		"stopNetScalerVpx",
		"updateGlobalLoadBalancerRule",
		"updateLBHealthCheckPolicy",
		"updateLBStickinessPolicy",
		"updateLoadBalancer",
		"updateLoadBalancerRule",
		"uploadSslCert",
	},
	"NetworkService": {
		"addNetworkServiceProvider",
		"addOpenDaylightController",
		"changeBgpPeersForNetwork",
		"createIpv4SubnetForGuestNetwork",
		"createNetwork",
		"createPhysicalNetwork",
		"createServiceInstance",
		"createStorageNetworkIpRange",
		"dedicatePublicIpRange",
		"deleteIpv4SubnetForGuestNetwork",
		"deleteNetwork",
		"deleteNetworkServiceProvider",
		"deleteOpenDaylightController",
		"deletePhysicalNetwork",
		"deleteStorageNetworkIpRange",
		"listIpv4SubnetsForGuestNetwork",
		"listNetworkIsolationMethods",
		"listNetworkProtocols",
		"listNetworkServiceProviders",
		"listNetworks",
		"listNiciraNvpDeviceNetworks",
		"listOpenDaylightControllers",
		"listPaloAltoFirewallNetworks",
		"listPhysicalNetworks",
		"listStorageNetworkIpRange",
		"listSupportedNetworkServices",
		"migrateNetwork",
		"releasePublicIpRange",
		"restartNetwork",
		"updateNetwork",
		"updateNetworkServiceProvider",
		"updatePhysicalNetwork",
		"updateStorageNetworkIpRange",
		"deleteGuestNetworkIpv6Prefix",
		"createGuestNetworkIpv6Prefix",
		"listGuestNetworkIpv6Prefixes",
		"createNetworkPermissions",
		"resetNetworkPermissions",
		"listNetworkPermissions",
		"removeNetworkPermissions",
	},
	"VirtualMachineService": {
		"addNicToVirtualMachine",
		"assignVirtualMachine",
		"changeServiceForVirtualMachine",
		"cleanVMReservations",
		"deployVirtualMachine",
		"destroyVirtualMachine",
		"expungeVirtualMachine",
		"getVMPassword",
		"listVirtualMachines",
		"listVirtualMachinesMetrics",
		"listVmsForImport",
		"migrateVirtualMachine",
		"migrateVirtualMachineWithVolume",
		"rebootVirtualMachine",
		"recoverVirtualMachine",
		"removeNicFromVirtualMachine",
		"resetPasswordForVirtualMachine",
		"resetUserDataForVirtualMachine",
		"restoreVirtualMachine",
		"scaleVirtualMachine",
		"startVirtualMachine",
		"stopVirtualMachine",
		"updateDefaultNicForVirtualMachine",
		"updateVirtualMachine",
		"listVirtualMachinesUsageHistory",
		"importVm",
		"unmanageVirtualMachine",
		"listUnmanagedInstances",
		"importUnmanagedInstance",
		"createVMSchedule",
		"updateVMSchedule",
		"listVMSchedule",
		"deleteVMSchedule",
	},
	"VPNService": {
		"addVpnUser",
		"createRemoteAccessVpn",
		"createVpnConnection",
		"createVpnCustomerGateway",
		"createVpnGateway",
		"deleteRemoteAccessVpn",
		"deleteVpnConnection",
		"deleteVpnCustomerGateway",
		"deleteVpnGateway",
		"listRemoteAccessVpns",
		"listVpnConnections",
		"listVpnCustomerGateways",
		"listVpnGateways",
		"listVpnUsers",
		"removeVpnUser",
		"resetVpnConnection",
		"updateRemoteAccessVpn",
		"updateVpnConnection",
		"updateVpnCustomerGateway",
		"updateVpnGateway",
	},
	"FirewallService": {
		"addPaloAltoFirewall",
		"configurePaloAltoFirewall",
		"createEgressFirewallRule",
		"createFirewallRule",
		"createPortForwardingRule",
		"createRoutingFirewallRule",
		"deleteEgressFirewallRule",
		"deleteFirewallRule",
		"deletePaloAltoFirewall",
		"deletePortForwardingRule",
		"deleteRoutingFirewallRule",
		"listEgressFirewallRules",
		"listFirewallRules",
		"listPaloAltoFirewalls",
		"listPortForwardingRules",
		"listRoutingFirewallRules",
		"updateEgressFirewallRule",
		"updateFirewallRule",
		"updatePortForwardingRule",
		"listIpv6FirewallRules",
		"createIpv6FirewallRule",
		"updateIpv6FirewallRule",
		"deleteIpv6FirewallRule",
		"updateRoutingFirewallRule",
	},
	"AutoScaleService": {
		"createAutoScalePolicy",
		"createAutoScaleVmGroup",
		"createAutoScaleVmProfile",
		"createCondition",
		"createCounter",
		"deleteAutoScalePolicy",
		"deleteAutoScaleVmGroup",
		"deleteAutoScaleVmProfile",
		"deleteCondition",
		"deleteCounter",
		"disableAutoScaleVmGroup",
		"enableAutoScaleVmGroup",
		"listAutoScalePolicies",
		"listAutoScaleVmGroups",
		"listAutoScaleVmProfiles",
		"listConditions",
		"listCounters",
		"updateAutoScalePolicy",
		"updateAutoScaleVmGroup",
		"updateAutoScaleVmProfile",
		"updateCondition",
	},
	"HostService": {
		"addBaremetalHost",
		"addGloboDnsHost",
		"addHost",
		"addSecondaryStorage",
		"cancelHostMaintenance",
		"configureHAForHost",
		"enableHAForHost",
		"dedicateHost",
		"deleteHost",
		"disableHAForHost",
		"disableOutOfBandManagementForHost",
		"enableOutOfBandManagementForHost",
		"findHostsForMigration",
		"listDedicatedHosts",
		"listHostTags",
		"listHosts",
		"listHostsMetrics",
		"prepareHostForMaintenance",
		"reconnectHost",
		"releaseDedicatedHost",
		"releaseHostReservation",
		"updateHost",
		"updateHostPassword",
		"migrateSecondaryStorageData",
		"cancelHostAsDegraded",
		"listHostHAProviders",
		"listSecondaryStorageSelectors",
		"createSecondaryStorageSelector",
		"removeSecondaryStorageSelector",
		"listHostHAResources",
		"declareHostAsDegraded",
		"updateSecondaryStorageSelector",
	},
	"VolumeService": {
		"attachVolume",
		"changeOfferingForVolume",
		"checkVolume",
		"createVolume",
		"deleteVolume",
		"destroyVolume",
		"detachVolume",
		"extractVolume",
		"getPathForVolume",
		"getUploadParamsForVolume",
		"getVolumeiScsiName",
		"importVolume",
		"listElastistorVolume",
		"listVolumes",
		"listVolumesForImport",
		"listVolumesMetrics",
		"migrateVolume",
		"recoverVolume",
		"resizeVolume",
		"unmanageVolume",
		"updateVolume",
		"uploadVolume",
		"listVolumesUsageHistory",
		"assignVolume",
		"restoreVolumeFromBackupAndAttachToVM",
	},
	"VPCService": {
		"createPrivateGateway",
		"createStaticRoute",
		"createVPC",
		"createVPCOffering",
		"deletePrivateGateway",
		"deleteStaticRoute",
		"deleteVPC",
		"deleteVPCOffering",
		"listPrivateGateways",
		"listStaticRoutes",
		"listVPCOfferings",
		"listVPCs",
		"migrateVPC",
		"restartVPC",
		"updateVPC",
		"updateVPCOffering",
	},
	"TemplateService": {
		"copyTemplate",
		"createTemplate",
		"deleteTemplate",
		"extractTemplate",
		"getUploadParamsForTemplate",
		"listTemplatePermissions",
		"listTemplates",
		"prepareTemplate",
		"registerTemplate",
		"updateTemplate",
		"updateTemplatePermissions",
		"upgradeRouterTemplate",
		"linkUserDataToTemplate",
	},
	"AccountService": {
		"createAccount",
		"deleteAccount",
		"disableAccount",
		"enableAccount",
		"isAccountAllowedToCreateOfferingsWithTags",
		"linkAccountToLdap",
		"listAccounts",
		"listProjectAccounts",
		"lockAccount",
		"markDefaultZoneForAccount",
		"updateAccount",
	},
	"ZoneService": {
		"createIpv4SubnetForZone",
		"createZone",
		"dedicateIpv4SubnetForZone",
		"dedicateZone",
		"deleteZone",
		"deleteIpv4SubnetForZone",
		"disableOutOfBandManagementForZone",
		"enableOutOfBandManagementForZone",
		"disableHAForZone",
		"enableHAForZone",
		"listDedicatedZones",
		"listIpv4SubnetsForZone",
		"listZones",
		"listZonesMetrics",
		"releaseDedicatedZone",
		"releaseIpv4SubnetForZone",
		"updateZone",
		"listVmwareDcVms",
		"addVmwareDc",
		"listVmwareDcs",
		"removeVmwareDc",
		"updateIpv4SubnetForZone",
		"updateVmwareDc",
	},
	"UsageService": {
		"addTrafficMonitor",
		"addTrafficType",
		"deleteTrafficMonitor",
		"deleteTrafficType",
		"generateUsageRecords",
		"listTrafficMonitors",
		"listTrafficTypeImplementors",
		"listTrafficTypes",
		"listUsageRecords",
		"listUsageTypes",
		"removeRawUsageRecords",
		"updateTrafficType",
		"listUsageServerMetrics",
	},
	"SnapshotService": {
		"archiveSnapshot",
		"copySnapshot",
		"createSnapshot",
		"createSnapshotFromVMSnapshot",
		"createSnapshotPolicy",
		"createVMSnapshot",
		"deleteSnapshot",
		"deleteSnapshotPolicies",
		"deleteVMSnapshot",
		"extractSnapshot",
		"listSnapshotPolicies",
		"listSnapshots",
		"listVMSnapshot",
		"revertSnapshot",
		"revertToVMSnapshot",
		"updateSnapshotPolicy",
	},
	"UserService": {
		"createUser",
		"deleteUser",
		"disableUser",
		"enableUser",
		"getUser",
		"getUserKeys",
		"getVirtualMachineUserData",
		"listUserTwoFactorAuthenticatorProviders",
		"listUsers",
		"lockUser",
		"registerUserKeys",
		"updateUser",
		"listUserData",
		"deleteUserData",
		"registerUserData",
		"moveUser",
		"setupUserTwoFactorAuthentication",
		"validateUserTwoFactorAuthenticationCode",
		"verifyOAuthCodeAndGetUser",
	},
	"LDAPService": {
		"addLdapConfiguration",
		"deleteLdapConfiguration",
		"importLdapUsers",
		"ldapConfig",
		"ldapCreateAccount",
		"ldapRemove",
		"linkDomainToLdap",
		"listLdapConfigurations",
		"listLdapUsers",
		"searchLdap",
	},
	"ISOService": {
		"attachIso",
		"copyIso",
		"deleteIso",
		"detachIso",
		"extractIso",
		"getUploadParamsForIso",
		"listIsoPermissions",
		"listIsos",
		"registerIso",
		"updateIso",
		"updateIsoPermissions",
	},
	"IPQuarantineService": {
		"listQuarantinedIps",
		"removeQuarantinedIp",
		"updateQuarantinedIp",
	},
	"RouterService": {
		"changeServiceForRouter",
		"configureVirtualRouterElement",
		"createVirtualRouterElement",
		"destroyRouter",
		"getRouterHealthCheckResults",
		"listRouters",
		"listVirtualRouterElements",
		"rebootRouter",
		"startRouter",
		"stopRouter",
	},
	"ProjectService": {
		"activateProject",
		"addAccountToProject",
		"addUserToProject",
		"createProject",
		"deleteAccountFromProject",
		"deleteUserFromProject",
		"deleteProject",
		"deleteProjectInvitation",
		"listProjectInvitations",
		"listProjects",
		"suspendProject",
		"updateProject",
		"updateProjectInvitation",
		"listProjectRolePermissions",
		"createProjectRolePermission",
		"updateProjectRolePermission",
		"deleteProjectRolePermission",
		"createProjectRole",
		"updateProjectRole",
		"deleteProjectRole",
	},
	"PoolService": {
		"createStoragePool",
		"deleteStoragePool",
		"findStoragePoolsForMigration",
		"listElastistorPool",
		"listStoragePools",
		"syncStoragePool",
		"updateStoragePool",
	},
	"NetworkACLService": {
		"createNetworkACL",
		"createNetworkACLList",
		"deleteNetworkACL",
		"deleteNetworkACLList",
		"listNetworkACLLists",
		"listNetworkACLs",
		"moveNetworkAclItem",
		"replaceNetworkACLList",
		"updateNetworkACLItem",
		"updateNetworkACLList",
	},
	"GuestOSService": {
		"addGuestOs",
		"addGuestOsMapping",
		"listGuestOsMapping",
		"listOsCategories",
		"listOsTypes",
		"removeGuestOs",
		"removeGuestOsMapping",
		"updateGuestOs",
		"updateGuestOsMapping",
		"getHypervisorGuestOsNames",
	},
	"ClusterService": {
		"addCluster",
		"dedicateCluster",
		"deleteCluster",
		"disableOutOfBandManagementForCluster",
		"enableOutOfBandManagementForCluster",
		"enableHAForCluster",
		"executeClusterDrsPlan",
		"generateClusterDrsPlan",
		"disableHAForCluster",
		"listClusters",
		"listClusterDrsPlan",
		"listClustersMetrics",
		"listDedicatedClusters",
		"releaseDedicatedCluster",
		"updateCluster",
	},
	"BaremetalService": {
		"addBaremetalDhcp",
		"addBaremetalPxeKickStartServer",
		"addBaremetalPxePingServer",
		"addBaremetalRct",
		"deleteBaremetalRct",
		"listBaremetalDhcp",
		"listBaremetalPxeServers",
		"listBaremetalRct",
		"notifyBaremetalProvisionDone",
	},
	"SystemVMService": {
		"changeServiceForSystemVm",
		"destroySystemVm",
		"listSystemVms",
		"listSystemVmsUsageHistory",
		"migrateSystemVm",
		"rebootSystemVm",
		"scaleSystemVm",
		"startSystemVm",
		"stopSystemVm",
		"patchSystemVm",
	},
	"RoleService": {
		"createRole",
		"createRolePermission",
		"deleteRole",
		"deleteRolePermission",
		"disableRole",
		"enableRole",
		"importRole",
		"listRolePermissions",
		"listRoles",
		"updateRole",
		"updateRolePermission",
		"listProjectRoles",
	},
	"ImageStoreService": {
		"addImageStore",
		"addImageStoreS3",
		"createSecondaryStagingStore",
		"deleteImageStore",
		"deleteSecondaryStagingStore",
		"listImageStores",
		"listSecondaryStagingStores",
		"migrateResourceToAnotherSecondaryStorage",
		"updateCloudToUseObjectStore",
		"listImageStoreObjects",
		"updateImageStore",
		"downloadImageStoreObject",
	},
	"AuthenticationService": {
		"login",
		"logout",
		"oauthlogin",
	},
	"SecurityGroupService": {
		"authorizeSecurityGroupEgress",
		"authorizeSecurityGroupIngress",
		"createSecurityGroup",
		"deleteSecurityGroup",
		"listSecurityGroups",
		"revokeSecurityGroupEgress",
		"revokeSecurityGroupIngress",
		"updateSecurityGroup",
	},
	"QuotaService": {
		"quotaBalance",
		"quotaCredits",
		"quotaIsEnabled",
		"quotaStatement",
		"quotaSummary",
		"quotaTariffCreate",
		"quotaTariffDelete",
		"quotaTariffList",
		"quotaTariffUpdate",
		"quotaUpdate",
	},
	"PodService": {
		"createManagementNetworkIpRange",
		"createPod",
		"dedicatePod",
		"deleteManagementNetworkIpRange",
		"deletePod",
		"listDedicatedPods",
		"listPods",
		"releaseDedicatedPod",
		"updatePod",
		"updatePodManagementNetworkIpRange",
	},
	"VLANService": {
		"createVlanIpRange",
		"dedicateGuestVlanRange",
		"deleteVlanIpRange",
		"listDedicatedGuestVlanRanges",
		"listVlanIpRanges",
		"releaseDedicatedGuestVlanRange",
		"listGuestVlans",
		"updateVlanIpRange",
	},
	"UCSService": {
		"addUcsManager",
		"associateUcsProfileToBlade",
		"deleteUcsManager",
		"listUcsBlades",
		"listUcsManagers",
		"listUcsProfiles",
	},
	"InternalLBService": {
		"configureInternalLoadBalancerElement",
		"createInternalLoadBalancerElement",
		"listInternalLoadBalancerElements",
		"listInternalLoadBalancerVMs",
		"startInternalLoadBalancerVM",
		"stopInternalLoadBalancerVM",
	},
	"SSHService": {
		"createSSHKeyPair",
		"deleteSSHKeyPair",
		"listSSHKeyPairs",
		"registerSSHKeyPair",
		"resetSSHKeyForVirtualMachine",
	},
	"NATService": {
		"createIpForwardingRule",
		"deleteIpForwardingRule",
		"disableStaticNat",
		"enableStaticNat",
		"listIpForwardingRules",
	},
	"LimitService": {
		"getApiLimit",
		"listResourceLimits",
		"resetApiLimit",
		"updateResourceCount",
		"updateResourceLimit",
	},
	"DomainService": {
		"createDomain",
		"deleteDomain",
		"listDomainChildren",
		"listDomains",
		"moveDomain",
		"updateDomain",
	},
	"AffinityGroupService": {
		"createAffinityGroup",
		"deleteAffinityGroup",
		"listAffinityGroupTypes",
		"listAffinityGroups",
		"updateVMAffinityGroup",
	},
	"VMGroupService": {
		"createInstanceGroup",
		"deleteInstanceGroup",
		"listInstanceGroups",
		"updateInstanceGroup",
	},
	"ServiceOfferingService": {
		"createServiceOffering",
		"deleteServiceOffering",
		"listServiceOfferings",
		"updateServiceOffering",
	},
	"ResourcetagsService": {
		"createTags",
		"deleteTags",
		"listStorageTags",
		"listTags",
	},
	"ResourcemetadataService": {
		"addResourceDetail",
		"listDetailOptions",
		"getVolumeSnapshotDetails",
		"listResourceDetails",
		"removeResourceDetail",
	},
	"RegionService": {
		"addRegion",
		"listRegions",
		"removeRegion",
		"updateRegion",
	},
	"NicService": {
		"addIpToNic",
		"listNics",
		"removeIpFromNic",
		"updateVmNicIp",
	},
	"NetworkOfferingService": {
		"createNetworkOffering",
		"deleteNetworkOffering",
		"listNetworkOfferings",
		"updateNetworkOffering",
	},
	"EventService": {
		"archiveEvents",
		"deleteEvents",
		"listEventTypes",
		"listEvents",
	},
	"DiskOfferingService": {
		"createDiskOffering",
		"deleteDiskOffering",
		"listDiskOfferings",
		"updateDiskOffering",
	},
	"ConfigurationService": {
		"listCapabilities",
		"listConfigurationGroups",
		"listConfigurations",
		"listDeploymentPlanners",
		"updateConfiguration",
		"resetConfiguration",
		"updateStorageCapabilities",
	},
	"BackupService": {
		"addBackupRepository",
		"createBackup",
		"createBackupSchedule",
		"createVMFromBackup",
		"deleteBackup",
		"deleteBackupOffering",
		"deleteBackupRepository",
		"deleteBackupSchedule",
		"importBackupOffering",
		"listBackupOfferings",
		"listBackupProviderOfferings",
		"listBackupProviders",
		"listBackupRepositories",
		"listBackupSchedule",
		"listBackups",
		"restoreBackup",
		"updateBackupOffering",
		"updateBackupSchedule",
	},
	"BrocadeVCSService": {
		"addBrocadeVcsDevice",
		"deleteBrocadeVcsDevice",
		"listBrocadeVcsDeviceNetworks",
		"listBrocadeVcsDevices",
	},
	"AlertService": {
		"archiveAlerts",
		"deleteAlerts",
		"generateAlert",
		"listAlerts",
		"listAlertTypes",
	},
	"AddressService": {
		"acquirePodIpAddress",
		"associateIpAddress",
		"disassociateIpAddress",
		"listPublicIpAddresses",
		"updateIpAddress",
		"releaseIpAddress",
		"releasePodIpAddress",
		"reserveIpAddress",
	},
	"StoragePoolService": {
		"cancelStorageMaintenance",
		"changeStoragePoolScope",
		"enableStorageMaintenance",
		"listAffectedVmsForStorageScopeChange",
		"listStorageProviders",
		"listObjectStoragePools",
		"listStoragePoolObjects",
		"updateObjectStoragePool",
		"addObjectStoragePool",
		"deleteObjectStoragePool",
		"listStoragePoolsMetrics",
	},
	"PortableIPService": {
		"createPortableIpRange",
		"deletePortableIpRange",
		"listPortableIpRanges",
	},
	"OutofbandManagementService": {
		"changeOutOfBandManagementPassword",
		"configureOutOfBandManagement",
		"issueOutOfBandManagementPowerAction",
	},
	"NiciraNVPService": {
		"addNiciraNvpDevice",
		"deleteNiciraNvpDevice",
		"listNiciraNvpDevices",
	},
	"NetworkDeviceService": {
		"addNetworkDevice",
		"deleteNetworkDevice",
		"listNetworkDevice",
	},
	"HypervisorService": {
		"listHypervisorCapabilities",
		"listHypervisors",
		"updateHypervisorCapabilities",
	},
	"BigSwitchBCFService": {
		"addBigSwitchBcfDevice",
		"deleteBigSwitchBcfDevice",
		"listBigSwitchBcfDevices",
	},
	"SwiftService": {
		"addSwift",
		"listSwifts",
	},
	"OvsElementService": {
		"configureOvsElement",
		"listOvsElements",
	},
	"AsyncjobService": {
		"listAsyncJobs",
		"queryAsyncJobResult",
	},
	"StratosphereSSPService": {
		"addStratosphereSsp",
		"deleteStratosphereSsp",
	},
	"SystemCapacityService": {
		"listCapacity",
	},
	"CloudIdentifierService": {
		"getCloudIdentifier",
	},
	"CertificateService": {
		"issueCertificate",
		"listCAProviders",
		"listCaCertificate",
		"listTemplateDirectDownloadCertificates",
		"provisionCertificate",
		"provisionTemplateDirectDownloadCertificate",
		"revokeCertificate",
		"revokeTemplateDirectDownloadCertificate",
		"uploadCustomCertificate",
		"uploadTemplateDirectDownloadCertificate",
	},
	"APIDiscoveryService": {
		"listApis",
	},
	"AnnotationService": {
		"addAnnotation",
		"listAnnotations",
		"removeAnnotation",
		"updateAnnotationVisibility",
	},
	"KubernetesService": {
		"addKubernetesSupportedVersion",
		"createKubernetesCluster",
		"deleteKubernetesCluster",
		"deleteKubernetesSupportedVersion",
		"getKubernetesClusterConfig",
		"listKubernetesClusters",
		"listKubernetesSupportedVersions",
		"scaleKubernetesCluster",
		"startKubernetesCluster",
		"stopKubernetesCluster",
		"updateKubernetesSupportedVersion",
		"upgradeKubernetesCluster",
		"addVirtualMachinesToKubernetesCluster",
		"removeVirtualMachinesFromKubernetesCluster",
	},
	"InfrastructureUsageService": {
		"listDbMetrics",
	},
	"ConsoleEndpointService": {
		"createConsoleEndpoint",
	},
	"ObjectStoreService": {
		"createBucket",
		"deleteBucket",
		"updateBucket",
		"listBuckets",
	},
	"OauthService": {
		"listOauthProvider",
		"updateOauthProvider",
		"deleteOauthProvider",
	},
	"RegistrationService": {
		"registerOauthProvider",
	},
	"DiagnosticsService": {
		"getDiagnosticsData",
		"runDiagnostics",
	},
	"MetricsService": {
		"listInfrastructure",
	},
	"ASNumberService": {
		"listASNumbers",
		"releaseASNumber",
	},
	"ASNumberRangeService": {
		"createASNRange",
		"deleteASNRange",
		"listASNRanges",
	},
	"CloudianService": {
		"cloudianIsEnabled",
	},
	"ManagementService": {
		"cancelShutdown",
		"listManagementServers",
		"listManagementServersMetrics",
		"prepareForShutdown",
		"readyForShutdown",
		"triggerShutdown",
	},
	"MiscService": {
		"listElastistorInterface",
	},
	"NetscalerService": {
		"addNetscalerLoadBalancer",
		"configureNetscalerLoadBalancer",
		"deleteNetscalerControlCenter",
		"deleteNetscalerLoadBalancer",
		"listNetscalerControlCenter",
		"listNetscalerLoadBalancerNetworks",
		"listNetscalerLoadBalancers",
		"registerNetscalerControlCenter",
		"registerNetscalerServicePackage",
	},
	"ResourceIconService": {
		"deleteResourceIcon",
		"listResourceIcon",
		"uploadResourceIcon",
	},
	"ResourceService": {
		"purgeExpungedResources",
	},
	"RollingMaintenanceService": {
		"startRollingMaintenance",
	},
	"SharedFileSystemService": {
		"changeSharedFileSystemDiskOffering",
		"changeSharedFileSystemServiceOffering",
		"createSharedFileSystem",
		"destroySharedFileSystem",
		"expungeSharedFileSystem",
		"listSharedFileSystemProviders",
		"listSharedFileSystems",
		"recoverSharedFileSystem",
		"restartSharedFileSystem",
		"startSharedFileSystem",
		"stopSharedFileSystem",
		"updateSharedFileSystem",
	},
	"SolidFireService": {
		"getSolidFireAccountId",
		"getSolidFireVolumeAccessGroupIds",
		"getSolidFireVolumeSize",
	},
	"VirtualNetworkFunctionsService": {
		"deleteVnfTemplate",
		"deployVnfAppliance",
		"listVnfAppliances",
		"listVnfTemplates",
		"registerVnfTemplate",
		"updateVnfTemplate",
	},
	"WebhookService": {
		"createWebhook",
		"deleteWebhook",
		"deleteWebhookDelivery",
		"executeWebhookDelivery",
		"listWebhookDeliveries",
		"listWebhooks",
		"updateWebhook",
	},
}
